import { PERMISSIONS } from "./permissions";

export const ROLES: Record<string, string[]> = {
  "Operational Admin": [...PERMISSIONS],
  "Fleet Admin": [
    "vehicle:create",
    "vehicle:review",
    "vehicle:approve",
    "vehicle:logs",
    "vehicle:view",
    "vehicle:assign",
    "dashboard:view",
    "ticket:create",
    "ticket:view",
    "ticket:update",
    "notifications:manage",
    "reports:view",
    "customer:view",
    "booking:view",
    "booking:assign",
    "booking:update",
    "ride:view",
  ],
  "Driver Admin": [
    "driver:create",
    "driver:verify",
    "driver:train",
    "driver:approve",
    "driver:view",
    "driver:assign",
    "driver:edit",
    "driver:delete",
    "driver:logs",
    "vehicle:view",
    "vehicle:assign",
    "dashboard:view",
    "ticket:create",
    "ticket:view",
    "ticket:update",
    "customer:view",
    "booking:view",
    "booking:assign",
    "booking:update",
    "ride:create",
    "ride:view",
    "ride:update",
  ],
  "Driver Individual": [
    "dashboard:view",
    "driver:create",
    "driver:view",
    "driver:edit",
    "ticket:create",
    "ticket:view",
    "ticket:update",
  ],
  "Fleet Individual": [
    "dashboard:view",
    "vehicle:view",
    "ticket:create",
    "ticket:view",
    "ticket:update",
  ],
  "Team": [
    "dashboard:view",
    "ticket:create",
    "ticket:view",
    "ticket:update",
    "booking:create",
    "booking:view",
    "booking:assign",
    "booking:update",
    "ride:create",
    "ride:view",
    "ride:update",
    "customer:view",
    "driver:view",
    "driver:verify",
    "driver:approve",
    "vehicle:view",
    "vehicle:review",
    "vehicle:approve",
    "reports:view",
    "notifications:manage",
  ],
};

